### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by lordone24** [henrytao-me/smooth-app-bar-layout#83] opened 2016-02-26 10:09 UTC
•Remember to set  android:minHeight  for  me.henrytao.smoothappbarlayout.SmoothAppBarLayout  in layout file if you use  ViewPager .

I did like below, but it din't work. what does it mean? please help......

android:minHeight="smoothappbarlayout.SmoothAppBarLayout"

**Comment by henrytao-me** [comment] 2016-02-28 22:18
Can you post your layout here? 

This is what I mean https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/sample%2Fsrc%2Fmain%2Fres%2Flayout%2Factivity_smooth_view_pager.xml#L31

**Comment by lordone24** [comment] 2016-02-29 02:12
Thank you for reply.

Here is my source of Appbarlayout. 
It doesn't work SmoothAppBarLayout with  viewpager.
(view pager source is next comment)

``` xml
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:custom="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <me.henrytao.smoothappbarlayout.SmoothAppBarLayout
        android:id="@+id/smooth_app_bar_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:minHeight="?attr/actionBarSize">

    <android.support.design.widget.CollapsingToolbarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:contentScrim="?attr/colorPrimary"
            app:layout_scrollFlags="scroll|exitUntilCollapsed"
            android:id="@+id/collapsing_toolbar">

        <com.daimajia.slider.library.SliderLayout
                android:id="@+id/slider"
                android:layout_width="match_parent"
                custom:pager_animation="Accordion"
                custom:auto_cycle="true"
                custom:indicator_visibility="visible"
                custom:pager_animation_span="1100"
                android:layout_height="200dp"/>

            <com.daimajia.slider.library.Indicators.PagerIndicator
                android:id="@+id/custom_indicator2"
                style="@style/AndroidImageSlider_Corner_Oval_Orange"
                android:layout_centerHorizontal="true"
                android:layout_alignParentBottom="true"
                android:layout_marginBottom="20dp" />
            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
                app:layout_collapseMode="pin" />

        </android.support.design.widget.CollapsingToolbarLayout>

        <android.support.design.widget.TabLayout
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="@color/white"
            app:tabMode="fixed"
            app:tabGravity="fill"/>

    </me.henrytao.smoothappbarlayout.SmoothAppBarLayout>

    <android.support.v4.view.ViewPager
        android:id="@+id/viewpager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"/>

</android.support.design.widget.CoordinatorLayout>
```

**Comment by lordone24** [comment] 2016-02-29 02:14
``` xml
<android.support.v4.widget.NestedScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fillViewport="true">

    <LinearLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"
            android:layout_marginTop="10dp"
            android:paddingLeft="5dp"
            android:textSize="15sp"
            android:textStyle="bold"
            android:textColor="@android:color/holo_blue_dark" />

        </LinearLayout>

        <com.weekensoft.gop.util.NestedListView
            android:id="@+id/nestedListView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="5dp"
            android:background="@color/white"
            android:drawSelectorOnTop="false" />

</android.support.v4.widget.NestedScrollView>
```

**Comment by henrytao-me** [comment] 2016-02-29 02:34
Hi @lordone24 

You can take a look at my examples in sample module. Below is my proposal changes. There are few notes here: 
- `ViewPager` should be declared before `SmoothAppBarLayout`. 
- You can use actionBarSize for TabLayout. However, according to Google Material Specs, it should be a bit smaller which is secondaryActionBarSize (check my sample module to see its values). 

If below code doesn't work, please send me a video to illustrate your issue. ;)

``` xml
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:fitsSystemWindows="true"
  xmlns:custom="http://schemas.android.com/apk/res-auto">

  <android.support.v4.view.ViewPager
    android:id="@+id/viewpager"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layout_behavior="@string/appbar_scrolling_view_behavior" />

  <me.henrytao.smoothappbarlayout.SmoothAppBarLayout
    android:id="@+id/smooth_app_bar_layout"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:minHeight="?attr/actionBarSize">

    <android.support.design.widget.CollapsingToolbarLayout
      android:id="@+id/collapsing_toolbar"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      app:contentScrim="?attr/colorPrimary"
      app:layout_scrollFlags="scroll|exitUntilCollapsed">

      <com.daimajia.slider.library.SliderLayout
        android:id="@+id/slider"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        custom:auto_cycle="true"
        custom:indicator_visibility="visible"
        custom:pager_animation="Accordion"
        custom:pager_animation_span="1100" />

      <com.daimajia.slider.library.Indicators.PagerIndicator
        android:id="@+id/custom_indicator2"
        android:layout_alignParentBottom="true"
        android:layout_centerHorizontal="true"
        android:layout_marginBottom="20dp"
        style="@style/AndroidImageSlider_Corner_Oval_Orange" />

      <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        app:layout_collapseMode="pin"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />
    </android.support.design.widget.CollapsingToolbarLayout>

    <android.support.design.widget.TabLayout
      android:id="@+id/tabs"
      android:layout_width="match_parent"
      android:layout_height="?attr/actionBarSize"
      android:background="@color/white"
      app:tabGravity="fill"
      app:tabMode="fixed" />
  </me.henrytao.smoothappbarlayout.SmoothAppBarLayout>
</android.support.design.widget.CoordinatorLayout>
```

**Comment by lordone24** [comment] 2016-02-29 07:34
It also doesn't work.  (ViewPager be declared before  SmoothAppBarLayout)
and try minheight=48dp (your secondaryActionBarSize) but no changes.
The problem is CollapsingToolbarLayout dosen't move. it is fixed when use SmoothAppBarLayout.
(scrolling of contents in viewpager well, tab movement well)

Although I saw not only your source module but downloading entired zip file, I can not resolve.
It works properly in google normal conditions like android.support.design.widget.AppBarLayout , android.support.design.widget.CollapsingToolbarLayout.

I can not attach video immediately so please let me know your other opinions.

**Comment by henrytao-me** [comment] 2016-02-29 07:46
Hi @lordone24 

You can post the video to youtube and share me a link. It's interesting to know what the issue. Also, please provide more information about your project: 
- version of AppCompat
- version of SmoothAppBarLayout

**Comment by lordone24** [comment] 2016-02-29 09:07
Hi @henrytao-me 

I uploaded vedio at Youtube. Additionally, I found viewpager scrolling is also have problem in the SmoothAppBarLayout.

Please check below link.
. Appcompat-v7:23.1.1
. version of SmoothAppBarLayout : tried both 0.2.3 and 0.2.2

https://youtu.be/ejKi1wg4OPI
https://youtu.be/z5A40N32Kd0

**Comment by henrytao-me** [comment] 2016-02-29 09:16
Hi @lordone24, 

I see what you want to do. It should work. Please try latest version of SmoothAppBarLayout which is `1.0.4`. 

Cheers, 
Henry

**Comment by lordone24** [comment] 2016-02-29 10:13
Hi @henrytao-me

Scrolling is good at ver1.0.4. thank you so much.
However There are some problems too.
1. It should not be up&down in the viewpager until end of SmoothAppBarLayout movement, but viewpager scrolling also move at first touch.
2. In my third tab, I don't know why toolbar diasappear when scroll-up.

pleaer check below linked video.
https://youtu.be/bMV0Q_ixDBE

**Comment by henrytao-me** [comment] 2016-02-29 12:42
Hi @lordone24, 

It's by design. There is a trade off. You can only choose one of below cases: 

**Case 1 (current implementation):** Keep scrolling offset for each tab. This mean if you are in TabA, scroll to xA position. Then, you switch to TabB, scroll to xB position. Then, you switch back to TabA, it will keep xA position instead of scrolling to the top of A. It's only reset scrolling of TabA to 0 if you scroll to 0 on TabB before switching back to TabA. You see it a bit laggy when SmoothAppBarLayout is just half way down because it has to sync SmoothAppBarLayout with current Tab scroll offset. 

**Case 2 (likely will be included in next release):** Always reset offset after switching between tab. I think I don't need to explain. 

If you pay attention, you can see original AppBarLayout only has `enterAlways` style. If you use the same style on SmoothAppBarLayout, you won't see this issue. 

SmoothAppBarLayout uses different approach compared to original AppBarLayout and supports `exitUntilCollapsed`, `QuickReturn`, so that depending on your requirements and some compromises, you can just simply accept it. 

I will update 2nd case in the next release soon. I hope it solves your problem for now. 

Let me know if you have any further thoughts. 

Cheers, 
Henry

**Comment by lordone24** [comment] 2016-03-01 13:53
Hi @henrytao-me

First of all, I'm not good at English. So sorry about it.
Tab to Tab movement is not a problem.

I wonder why  ViewPager  should be declared before  SmoothAppBarLayout. 
In my original code, In case of Viewpager be declared after AppbarLayout, there is any problem except smooth scrolling CollapsingToolbarLayout. so I try to use your code...... 

However, If  ViewPager  be declared before  SmoothAppBarLayout or AppbarLayout, viewpager and Appbarl\Layout It seems to overlap. And If  ViewPager  be declared after  SmoothAppBarLayout, There are some scrolling problem like just above video.

I'm very confused about it ^^

**Comment by henrytao-me** [comment] 2016-03-01 14:01
Hi @lordone24 

Overlapping is acceptable and by design. With SmoothAppBarLayout you have to declare header view (either Header ViewHolder for RecyclerView or Header Spacing for NestedScrollView) in order to make it work perfectly. 

It's the best option if you can share your repo with me and tell me what you want to achieve. I am willing to fix it for you. 

Cheers, 
Henry

**Comment by henrytao-me** [comment] 2016-03-13 08:27
Hi @lordone24 

How's the issue? Can you close this issue if it works for you?

**Comment by lordone24** [comment] 2016-03-13 23:41
Hi @henrytao-me

No... Still It's not working. I think this is not a simple issue so proceeded other tasks.
I will ask you when the process again. Thank you very much for your attention.

**Comment by henrytao-me** [comment] 2016-03-14 01:34
Please keep me posted. We can do TeamViewer to investigate the issue. In the meantime, I will close this issue. 

Cheers, 
Henry

**Closed as completed by henrytao-me** 2016-03-14 01:34 UTC

**Comment by aahmad123121** [comment] 2016-08-12 09:22
Hi,
I am getting issue mentioned below while using smooth-app-bar-layout
 android.view.InflateException: Binary XML file line #13: Error inflating class me.henrytao.smoothappbarlayout.SmoothAppBarLayout

the dependency of smooth-app-bar-layout is design library and latest appcompat v 35 in eclipse
Hi, find out problem
